FROM node:20-alpine AS base
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"

RUN apk add --no-cache libc6-compat && \
corepack enable && \
npm  install -g pnpm turbo

FROM base AS builder
ARG APP=web
WORKDIR /app
COPY pnpm-lock.yaml ./pnpm-lock.yaml
COPY pnpm-workspace.yaml ./pnpm-workspace.yaml
COPY package.json ./package.json
COPY packages/ ./packages/
COPY apps/${APP}/package.json ./apps/${APP}/
RUN pnpm install --frozen-lockfile --force

FROM builder AS installer
ARG APP=web
WORKDIR /app 
COPY . .
COPY --from=builder /app/node_modules ./node_modules
WORKDIR /app/apps/${APP}
RUN pnpm run build
 
FROM installer AS runner
ARG APP=web
WORKDIR /app
 
RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs
USER nextjs

COPY --from=installer /app/node_modules ./node_modules
COPY --from=installer /app/apps/web/node_modules ./apps/web/node_modules  
COPY --from=installer /app/apps/web/next.config.js .
COPY --from=installer /app/apps/web/package.json .
 
COPY --from=installer --chown=nextjs:nodejs /app/apps/web/.next/standalone ./
COPY --from=installer --chown=nextjs:nodejs /app/apps/web/.next/static ./apps/web/.next/static
COPY --from=installer --chown=nextjs:nodejs /app/apps/web/public ./apps/web/public
WORKDIR /app/apps/${APP} 
EXPOSE 3000
ENV HOSTNAME=0.0.0.0
CMD ["node", "server.js"]