FROM node:latest AS base

FROM base AS builder
WORKDIR /app
RUN npm install -g turbo 
COPY . .
RUN turbo prune web --docker 

FROM base AS installer
WORKDIR /app
COPY --from=builder /app/out/json/ .
COPY package.json pnpm.lock* ./
COPY apps/${APP}/package.json ./apps/${APP}/
COPY pnpm-lock.yaml ./
COPY  pnpm-workspace.yaml ./
COPY packages/ ./packages/
RUN npm install 

FROM base AS runner
WORKDIR /app
COPY --from=installer /app/out/full/ .
COPY --from=installer /app/apps/web/.next/standalone ./
COPY --from=installer /app/apps/web/.next/static ./apps/web/.next/static
COPY --from=installer /app/apps/web/public ./apps/web/public

CMD node apps/web/server.js