FROM node:latest AS base

FROM base AS prunner
WORKDIR /app
RUN npm install -g turbo 
COPY . .

FROM base AS installer
WORKDIR /app
COPY --from=prunner /app/out/json/ .
COPY package.json pnpm.lock* ./
COPY apps/${APP}/package.json ./apps/${APP}/
COPY pnpm-lock.yaml ./
COPY  pnpm-workspace.yaml ./
COPY packages/ ./packages/
RUN pnpm install --filter=web...

FROM base AS  builder
WORKDIR /app
COPY --from=installer /app ./
WORKDIR /app/apps/web
RUN pnpm run build

FROM base AS runner
WORKDIR /app
COPY --from=builder /app/out/full/ .
COPY --from=builder /app/apps/web/.next/standalone ./
COPY --from=builder /app/apps/web/.next/static ./apps/web/.next/static
COPY --from=builder /app/apps/web/public ./apps/web/public

CMD node apps/web/server.js