FROM node:20.2-alpine3.17 as base
RUN npm install -g  pnpm turbo ts-node
FROM base AS installer
ARG APP=filehandler-server
WORKDIR /app
COPY package.json  ./
COPY pnpm-lock.yaml ./
COPY  pnpm-workspace.yaml ./
COPY apps/${APP}/package.json ./apps/${APP}/
COPY packages/ ./packages/
COPY .npmrc ./
COPY . .
RUN --mount=type=cache,id=pnpm,target=/root/.local/share/pnpm/store \
  pnpm install --frozen-lockfile 


FROM base AS runner
ARG APP=filehandler-server
WORKDIR /app
COPY --from=installer /app ./
WORKDIR /app/apps/${APP}


EXPOSE 3002
CMD ["pnpm", "run", "dev"] 
