FROM node:20.2-alpine3.17 as base
RUN npm install -g pnpm turbo

FROM base AS installer
ARG APP=ws-server
WORKDIR /app
COPY package.json pnpm.lock* ./
COPY pnpm-lock.yaml ./
COPY  pnpm-workspace.yaml ./
COPY apps/${APP}/package.json ./apps/${APP}/
COPY packages/ ./packages/
COPY .npmrc ./
RUN pnpm install --frozen-lockfile
COPY . .
FROM base AS builder
ARG APP=ws-server
WORKDIR /app
COPY --from=installer /app ./
RUN pnpm run build

FROM base AS runner
ARG APP=ws-server
WORKDIR /app
COPY --from=builder /app ./
RUN pnpm --filter prisma run generate
WORKDIR /app/apps/${APP}

EXPOSE 8080
CMD ["pnpm", "run", "start"] 

