services:
  notekafka1:
    image: bitnami/kafka:3.6.2-debian-12-r5
    container_name: notekafka1
    ports:
      - "9092:9092"
    env_file:
      - ./env.compose
    networks:
      - note-network
    volumes:
      - ./kafka_data3:/bitnami/kafka/data
    environment:
      KAFKA_CFG_NODE_ID: 1
      KAFKA_KRAFT_CLUSTER_ID: "42VMU-JcQ9-5wO8UzA-bAA"
      KAFKA_CFG_ADVERTISED_LISTENERS: INTERNAL://notekafka1:9092
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 1@notekafka1:9095,2@notekafka2:9095,3@notekafka3:9095,4@notekafka4:9095
    command: |
      bash -c "    
        
      rm -rf /kafka_data1/data/__cluster_metadata-0
       
      "
    profiles:
      - setup  

  notekafka2:
    image: bitnami/kafka:3.6.2-debian-12-r5
    container_name: notekafka2
    ports:
      - "9093:9092"
    env_file:
      - ./env.compose
    networks:
      - note-network
    volumes:
      - ./kafka_data3:/bitnami/kafka/data
    environment:
      KAFKA_CFG_NODE_ID: 2
      KAFKA_CFG_CLUSTER_ID: "42VMU-JcQ9-5wO8UzA-bAA"
      KAFKA_CFG_ADVERTISED_LISTENERS: INTERNAL://notekafka2:9092
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 1@notekafka1:9095,2@notekafka2:9095,3@notekafka3:9095,4@notekafka4:9095
    command: |
      bash -c "
      
      rm -rf /kafka_data2/data/__cluster_metadata-0
    
       
      "
    profiles:
      - setup  

  notekafka3:
    image: bitnami/kafka:3.6.2-debian-12-r5
    container_name: notekafka3
    restart: always
    ports:
      - "9094:9092"
    env_file:
      - ./env.compose
    networks:
      - note-network
    volumes:
      - ./kafka_data3:/bitnami/kafka/data
    environment:
      KAFKA_CFG_NODE_ID: 3
      KAFKA_CFG_CLUSTER_ID: "42VMU-JcQ9-5wO8UzA-bAA"
      KAFKA_CFG_ADVERTISED_LISTENERS: INTERNAL://notekafka3:9092
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 1@notekafka1:9095,2@notekafka2:9095,3@notekafka3:9095,4@notekafka4:9095
    command: |
      bash -c "
      
        echo 'Source metadata found, proceeding with copy...'
        
        # Remove existing metadata
        rm -rf /kafka_data3/data/__cluster_metadata-0
      "
    profiles:
      - setup
  
  notekafka4:
    image: bitnami/kafka:3.6.2-debian-12-r5
    container_name: notekafka4
    restart: always
    ports:
      - "9096:9092"
    env_file:
      - ./env.compose
    networks:
      - note-network
    volumes:
      - ./kafka_data3:/bitnami/kafka/data
    environment:
      KAFKA_CFG_NODE_ID: 4
      KAFKA_CFG_CLUSTER_ID: "42VMU-JcQ9-5wO8UzA-bAA"
      KAFKA_CFG_ADVERTISED_LISTENERS: INTERNAL://notekafka4:9092
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 1@notekafka1:9095,2@notekafka2:9095,3@notekafka3:9095,4@notekafka4:9095
    command: |
      bash -c "
      
        rm -rf /kafka_data4/data/__cluster_metadata-0
      "
    profiles:
      - setup

  nats-server:
    image: nats:latest
    container_name: nats-server
    ports:
      - "4222:4222"
      - "8222:8222"
    networks:
      - note-network
    volumes:
      - ./nats_data:/data
      - ./nats-server.conf:/etc/nats/nats-server.conf
    command: ["-c", "/etc/nats/nats-server.conf"]


  http-server:
    image: ${DOCKER_USERNAME}/http-server:latest
    container_name: http-server
    env_file:
      - ./env.compose
    ports:
      - "3001:3001"  
    environment:
      - DATABASE_URL=${DATABASE_URL}  
    networks:
      - note-network
    depends_on:
      - notekafka1
      - notekafka2
      - notekafka3
      - notekafka4
      - nats-server  

  filehandler-server:
    image: ${DOCKER_USERNAME}/filehandler-server:latest
    container_name: filehandler-server
    env_file:
      - ./env.compose
    ports:
      - "3002:3002"   
    networks:
      - note-network
    depends_on:
      - notekafka1
      - notekafka2
      - notekafka3
      - notekafka4
      - nats-server      

  worker-server:
    image: ${DOCKER_USERNAME}/worker-server:latest
    container_name: worker-server
    env_file:
      - ./env.compose
    ports:
      - "3003:3003"   
    networks:
      - note-network
    depends_on:
      - notekafka1
      - notekafka2
      - notekafka3
      - notekafka4
      - nats-server    

  ws-server:
    image: ${DOCKER_USERNAME}/ws-server:latest
    container_name: ws-server
    env_file:
      - ./env.compose
    ports:
      - "8080:8080"   
  
    networks:
      - note-network
    depends_on:
      - notekafka1
      - notekafka2
      - notekafka3
      - notekafka4
      - nats-server
      - worker-server    

  web:
    image: ${DOCKER_USERNAME}/web:latest
    container_name: web
    env_file:
      - ./env.compose
    ports:
      - "3000:3000"   
    networks:
      - note-network

networks:
  note-network:
    driver: bridge

volumes:
  kafka_data1:
  kafka_data2:
  kafka_data3:
  kafka_data4:    

