FROM node:20.2-alpine3.17 as base
RUN npm install -g pnpm turbo  ts-node 

FROM base AS installer
ARG APP=http-serve
WORKDIR /app
COPY package.json pnpm.lock* ./
COPY pnpm-lock.yaml ./
COPY  pnpm-workspace.yaml ./
COPY apps/${APP}/package.json ./apps/${APP}/
COPY packages/ ./packages/
COPY .npmrc ./
COPY . .
RUN pnpm install --frozen-lockfile
RUN pnpm --filter $APP prisma generate

FROM base AS runner
ARG APP=http-server
WORKDIR /app
COPY --from=installer /app    ./
WORKDIR /app/apps/${APP}


EXPOSE 3001
CMD ["pnpm", "run", "dev"] 
