FROM node:20.2-alpine3.17 as base
RUN npm install -g pnpm turbo
FROM base AS installer
ARG DATABASE_URL
ENV DATABASE_URL=${DATABASE_URL}
ARG APP=http-server
WORKDIR /app
COPY package.json  ./
COPY pnpm-lock.yaml ./
COPY  pnpm-workspace.yaml ./
COPY apps/${APP}/package.json ./apps/${APP}/
COPY packages/ ./packages/
COPY .npmrc ./
RUN pnpm install --frozen-lockfile 
RUN pnpm --filter $APP prisma generate
COPY . .

#############################################
FROM base AS builder
ARG APP=ws-server
WORKDIR /app
COPY --from=installer /app ./
RUN pnpm --filter prisma run generate
RUN pnpm run build
#############################################
FROM base AS runner
ARG APP=http-server
WORKDIR /app
COPY --from=builder /app    ./
WORKDIR /app/apps/${APP}


EXPOSE 3001
CMD ["pnpm", "run", "start"] 
