FROM node:20.2-alpine3.17 as base
RUN npm install -g pnpm turbo

FROM base AS prunner
ARG APP=http-server
WORKDIR /app
COPY . .
RUN turbo prune --scope=$APP --docker

FROM base AS installer
ARG DATABASE_URL
ENV DATABASE_URL=${DATABASE_URL}
ARG APP=http-server
WORKDIR /app
COPY --from=prunner /app/out/json/ .
COPY --from=prunner /app/out/full/ .
COPY package.json  ./
COPY pnpm-lock.yaml ./
COPY  pnpm-workspace.yaml ./
COPY apps/${APP}/package.json ./apps/${APP}/
COPY packages/ ./packages/
COPY .npmrc ./
RUN pnpm install --filter http-server
RUN pnpm --filter  prisma run generate

#############################################
FROM base AS builder
ARG APP=http-server
WORKDIR /app
COPY --from=installer /app ./
WORKDIR /app/apps/${APP}
RUN pnpm run build
#############################################
FROM base AS runner
ARG APP=http-server
WORKDIR /app
COPY --from=builder /app    ./
WORKDIR /app/apps/${APP}


EXPOSE 3001
CMD ["pnpm", "run", "start"] 
