FROM node:20.13.1-bookworm-slim as base
RUN apt-get update -y && apt-get install -y \
    openssl \
    libssl-dev \
    ca-certificates 
RUN npm install -g pnpm

FROM base AS installer
ARG APP=worker-server
WORKDIR /app
COPY package.json  ./
COPY pnpm-lock.yaml ./
COPY  pnpm-workspace.yaml ./
COPY apps/${APP}/package.json ./apps/${APP}/
COPY packages/ ./packages/
COPY .npmrc ./
COPY . .
RUN --mount=type=cache,id=pnpm,target=/root/.local/share/pnpm/store \
pnpm install --frozen-lockfile --force
RUN pnpm --filter  prisma run generate

FROM base AS runner
ARG APP=worker-server
WORKDIR /app
COPY --from=installer /app ./
WORKDIR /app/apps/${APP}

EXPOSE 3003
CMD ["pnpm", "run", "dev"] 
