FROM node:20.2-alpine3.17 as base
RUN npm install -g pnpm turbo

FROM base AS installer
ARG APP=ws-server
WORKDIR /app
COPY package.json pnpm.lock* ./
COPY pnpm-lock.yaml ./
COPY  pnpm-workspace.yaml ./
COPY apps/${APP}/package.json ./apps/${APP}/
COPY packages/ ./packages/
RUN pnpm install --frozen-lockfile
COPY .npmrc ./
COPY . .
RUN turbo prune $APP --docker
#############################################
FROM installer AS builder
ARG APP=web
WORKDIR /app
WORKDIR /app/apps/${APP}
RUN pnpm run build


#############################################
FROM builder AS runner
ARG APP=ws-server
WORKDIR /app
COPY --from=builder /app ./
WORKDIR /app/apps/${APP}

EXPOSE 8080
CMD ["pnpm", "run", "dev"] 

