FROM node:20.13.1-bookworm-slim AS base

RUN npm install -g pnpm
FROM base AS installer
ARG APP=ws-server
WORKDIR /app
COPY package.json ./
COPY pnpm-lock.yaml ./
COPY  pnpm-workspace.yaml ./
COPY apps/${APP}/package.json ./apps/${APP}/
COPY packages/ ./packages/
COPY .npmrc ./
COPY . .
RUN --mount=type=cache,id=pnpm,target=/root/.local/share/pnpm/store \
pnpm install --frozen-lockfile


FROM base AS runner
ARG APP=ws-server
WORKDIR /app
COPY --from=installer /app ./
WORKDIR /app/apps/${APP}

EXPOSE 8080
CMD ["pnpm", "run", "dev"] 

