FROM node:20.13.1-bookworm-slim as base
RUN npm install -g pnpm turbo

FROM base AS prunner
ARG APP=ws-server
WORKDIR /app
COPY . .
RUN turbo prune --scope=$APP --docker

FROM base AS installer
ARG APP=ws-server
WORKDIR /app

COPY --from=prunner /app/out/json/ .
COPY --from=prunner /app/out/full/ .
COPY package.json ./
COPY pnpm-lock.yaml ./
COPY  pnpm-workspace.yaml ./
COPY apps/${APP}/package.json ./apps/${APP}/
COPY packages/ ./packages/
RUN pnpm install --frozen-lockfile
COPY .npmrc ./

FROM base AS builder
ARG APP=ws-server
WORKDIR /app
COPY --from=installer /app ./
WORKDIR /app/apps/${APP}
RUN pnpm run build



FROM base AS runner
ARG APP=ws-server
WORKDIR /app
COPY --from=builder /app ./
WORKDIR /app/apps/${APP}

EXPOSE 8080
CMD ["pnpm", "run", "dev"] 

