on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

jobs:
  build-and-push:
    environment: production
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push http-server Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./apps/http-server/Dockerfile.prod
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/http-server:latest
            ${{ secrets.DOCKER_USERNAME }}/http-server:${{ github.sha }}
          build-args: |
            DATABASE_URL=${{ secrets.DATABASE_URL }}  

      - name: Build and push filehandler-server Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./apps/filehandler-server/Dockerfile.prod
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/filehandler-server:latest
            ${{secrets.DOCKER_USERNAME }}/filehandler-server:${{ github.sha }}

      - name: Build and push worker-server Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./apps/worker-server/Dockerfile.prod
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/worker-server:latest
            ${{ secrets.DOCKER_USERNAME }}/worker-server:${{ github.sha }}

          build-args: |
            DATABASE_URL=${{ secrets.DATABASE_URL }}  

      - name: Build and push ws-server Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./apps/ws-server/Dockerfile.prod
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/ws-server:latest
            ${{ secrets.DOCKER_USERNAME }}/ws-server:${{ github.sha }}

      - name: Build and push web Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./apps/web/Dockerfile.prod
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME}}/web:latest
            ${{ secrets.DOCKER_USERNAME }}/web:${{ github.sha }}

          build-args: |
            DATABASE_URL=${{ secrets.DATABASE_URL }}  
            NEXT_PUBLIC_FRONTEND_URL=${{secrets.NEXT_PUBLIC_FRONTEND_URL}}
            NEXT_PUBLIC_BACKEND_URL=${{secrets.NEXT_PUBLIC_BACKEND_URL}}
            NEXT_PUBLIC_WEBSOCKET_SERVER=${{secrets.NEXT_PUBLIC_WEBSOCKET_SERVER}}
            ACCESS_TOKEN_SECRET=${{secrets.ACCESS_TOKEN_SECRET}}
            REFRESH_TOKEN_SECRET=${{secrets.REFRESH_TOKEN_SECRET}}

  deploy:
    runs-on: ubuntu-latest
    environment: production
    needs: build-and-push
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Generate Nginx config from template
        run: |
          rm -rf build
          mkdir -p build
          chmod 777 build
          export API_DOMAIN=${{ secrets.API_DOMAIN }}
          export FRONTEND_DOMAIN=${{ secrets.FRONTEND_DOMAIN }}
          export WS_SERVER_DOMAIN=${{ secrets.WS_SERVER_DOMAIN }}
          export API_DOMAIN_PORT=${{ secrets.API_DOMAIN_PORT }}
          export FRONTEND_DOMAIN_PORT=${{ secrets.FRONTEND_DOMAIN_PORT }}
          export WS_SERVER_DOMAIN_PORT=${{ secrets.WS_SERVER_DOMAIN_PORT }}

          envsubst '${API_DOMAIN} ${FRONTEND_DOMAIN} ${WS_SERVER_DOMAIN} ${API_DOMAIN_PORT} ${FRONTEND_DOMAIN_PORT} ${WS_SERVER_DOMAIN_PORT}' \
          < nginx/nginx.conf.template > ./build/nginx.conf



      - name: Copy config to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "build/*"
          target: "~/nginx-temp"

      - name: Deploy to VM via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          
          script: |
            export API_DOMAIN="${{ secrets.API_DOMAIN }}"
            export FRONTEND_DOMAIN="${{ secrets.FRONTEND_DOMAIN }}"
            export WS_SERVER_DOMAIN="${{ secrets.WS_SERVER_DOMAIN }}"
            if ! command -v curl &> /dev/null; then
                sudo apt-get update
                sudo apt-get install -y curl
            fi

            if ! command -v node &> /dev/null; then
              curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash -
              sudo apt-get install -y nodejs
            else
              echo "Node.js already installed: $(node -v)"
            fi

            sudo apt-get update && sudo apt-get install -y docker.io
            sudo groupadd docker
            sudo usermod -aG docker $USER

            sudo apt-get update -y
            sudo apt-get install -y nginx
            sudo systemctl start nginx
            sudo mkdir -p /etc/nginx/conf.d
            sudo cp -f /home/ubuntu/nginx-temp/build/nginx.conf /etc/nginx/conf.d/app.conf  
            sudo rm -f /etc/nginx/sites-enabled/default
            sudo rm -f /etc/nginx/sites-available/default
            sudo apt install certbot python3-certbot-nginx -y

            sudo certbot --nginx -d ${{secrets.FRONTEND_DOMAIN}} -m ${{ secrets.SSL_EMAIL }} --agree-tos --non-interactive
            sudo certbot --nginx -d ${{secrets.API_DOMAIN}} -m ${{ secrets.SSL_EMAIL }} --agree-tos --non-interactive
            sudo certbot --nginx -d ${{secrets.WS_SERVER_DOMAIN}} -m ${{ secrets.SSL_EMAIL }} --agree-tos --non-interactive

            sudo certbot renew --deploy-hook "systemctl reload nginx"
            sudo nginx -t
            sudo systemctl reload nginx
            echo "Stopping all containers..."

            sudo docker stop $(sudo docker ps -q) || true

            echo "Removing all containers..."
            sudo docker rm -f $(sudo docker ps -aq) || true

            echo "Removing all images..."

            sudo docker rmi -f $(sudo docker images -q) || true   
            sudo docker system prune -af
            sudo docker network create note-network || true
            
            mkdir -p ~/kafka_data1
            mkdir -p ~/kafka_data2
            mkdir -p ~/kafka_data3
            sudo chown -R 1001:1001 ~/kafka_data1
            sudo chown -R 1001:1001 ~/kafka_data2
            sudo chown -R 1001:1001 ~/kafka_data3

            sudo rm env.http || true
            sudo rm env.redis || true
            echo "username=${{ secrets.username }}" >> env.redis
            echo "password=${{ secrets.password }}" >> env.redis
            echo "host=${{ secrets.host }}" >> env.redis
            echo "port=${{ secrets.port }}" >> env.redis
            echo "KAFKA_USERNAME=${{ secrets.KAFKA_USERNAME }}" >> env.redis
            echo "KAFKA_PASSWORD=${{ secrets.KAFKA_PASSWORD}}" >> env.redis
         
            echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}">> env.http
            echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY}}">> env.http
            echo "bucketName=${{ secrets.bucketName }}">> env.http
            echo "AWS_REGION=${{ secrets.AWS_REGION }}">> env.http
            echo "ACCESS_TOKEN_SECRET=${{ secrets.ACCESS_TOKEN_SECRET }}" >> env.http
            echo "ServerSideEncryption=${{ secrets.ServerSideEncryption }}">> env.http
            echo "REFRESH_TOKEN_SECRET=${{ secrets.REFRESH_TOKEN_SECRET }}">> env.http
            echo "NEXT_PUBLIC_FRONTEND_URL=${{ secrets.NEXT_PUBLIC_FRONTEND_URL }}">> env.http
            echo "KAFKA_USERNAME=${{ secrets.KAFKA_USERNAME }}" >> env.http
            echo "KAFKA_PASSWORD=${{ secrets.KAFKA_PASSWORD}}" >> env.http

           

            sudo rm -f env.kafka
            echo "KAFKA_CFG_PROCESS_ROLES=broker,controller">> env.kafka
            echo "KAFKA_ENABLE_KRAFT=yes" >> env.kafka
            echo "ALLOW_PLAINTEXT_LISTENER=yes">> env.kafka
            echo "KAFKA_CFG_DELETE_TOPIC_ENABLE=false">> env.kafka
            echo "KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true">> env.kafka
            echo "KAFKA_CFG_LOG_RETENTION_MS=180000" >> env.kafka
            echo "KAFKA_CFG_SASL_ENABLED_MECHANISMS=PLAIN" >> env.kafka
            echo "KAFKA_CFG_SASL_MECHANISM_INTER_BROKER_PROTOCOL=PLAIN" >> env.kafka
            echo "KAFKA_CFG_LISTENERS=INTERNAL://0.0.0.0:9092,CONTROLLER://0.0.0.0:9095" >> env.kafka
            echo "KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:SASL_PLAINTEXT,EXTERNAL:SASL_PLAINTEXT,CONTROLLER:SASL_PLAINTEXT" >> env.kafka
            echo "KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER" >> env.kafka
            echo "KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@notekafka1:9095,2@notekafka2:9095,3@notekafka3:9095" >> env.kafka
            echo "KAFKA_CFG_INTER_BROKER_LISTENER_NAME=INTERNAL" >> env.kafka
            echo "KAFKA_CFG_SASL_MECHANISM_CONTROLLER_PROTOCOL=PLAIN" >> env.kafka
            # echo "KAFKA_CFG_SECURITY_INTER_BROKER_PROTOCOL=SASL_PLAINTEXT" >> env.kafka
    
            # echo "KAFKA_CFG_AUTHORIZER_CLASS_NAME=org.apache.kafka.metadata.authorizer.StandardAuthorizer" >> env.kafka
            # echo "KAFKA_CFG_AUTHORIZER_CLASS_NAME=org.apache.kafka.metadata.authorizer.AclAuthorizer" >> env.kafka
            echo "KAFKA_CLIENT_USERS=${{secrets.KAFKA_USERNAME}}" >> env.kafka
            echo "KAFKA_CLIENT_PASSWORDS=${{secrets.KAFKA_PASSWORD}}" >> env.kafka
            echo "KAFKA_CFG_SASL_JAAS_CONFIG=org.apache.kafka.common.security.plain.PlainLoginModule required username=\"${{secrets.KAFKA_USERNAME}}\" password=\"${{secrets.KAFKA_PASSWORD}}\" user_admin=\"${{secrets.KAFKA_PASSWORD}}\" user_app=\"app-secret\";" >> env.kafka

            echo "KAFKA_CFG_LOG_RETENTION_CHECK_INTERVAL_MS=120000" >> env.kafka
            echo "KAFKA_CFG_LOG_RETENTION_MS=180000" >> env.kafka
            echo "KAFKA_CFG_LOG_SEGMENT_BYTES=1073741824" >> env.kafka
            echo "KAFKA_CFG_LOG_SEGMENT_DELETE_DELAY_MS=120000" >> env.kafka
            echo "KAFKA_CFG_LOG_RETENTION_BYTES=1073741824" >> env.kafka
            echo "KAFKA_CFG_LOG_CLEANUP_POLICY=delete" >> env.kafka
            
            IMAGE1=${{secrets.DOCKER_USERNAME }}/http-server:${{ github.sha }}
            IMAGE2=${{secrets.DOCKER_USERNAME }}/filehandler-server:${{ github.sha }}
            IMAGE3=${{secrets.DOCKER_USERNAME }}/worker-server:${{ github.sha }}
            IMAGE4=${{secrets.DOCKER_USERNAME }}/ws-server:${{ github.sha }}
            IMAGE5=${{secrets.DOCKER_USERNAME }}/web:${{ github.sha }}
            IMAGE6=bitnami/kafka:3.5.1
            IMAGE7=nats:latest

            echo "Pulling the  images from  docker hub"

            cat <<'EOF' > nats-server.conf
            server_name: nats-server

            authorization {
            user: natsuser
            password: natspassword
            timeout: 2
            }

            listen: 0.0.0.0:4222
            debug: true
            trace: false
            logtime: true

            max_connections: 1000
            max_payload: 64MB
            write_deadline: 2s

            http: 0.0.0.0:8222
            jetstream {
            store_dir: /data/jetstream
            max_mem: 200MB
            max_file: 0.4GB
            }
            EOF


            sudo docker pull $IMAGE1
            sudo docker pull $IMAGE2
            sudo docker pull $IMAGE3
            sudo docker pull $IMAGE4
            sudo docker pull $IMAGE5
            sudo docker pull $IMAGE6
            sudo docker pull $IMAGE7

            NETWORK="note-network"

      
            sudo docker run -d \
            -p 9092:9092 \
            --name notekafka1 \
            --restart always \
            --env-file env.kafka \
            -e "KAFKA_CFG_CLUSTER_ID=42VMU-JcQ9-5wO8UzA-bAA" \
            -e "KAFKA_CFG_NODE_ID=1" \
            -e "KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://notekafka1:9092" \
            -v $(pwd)/kafka_data1:/bitnami/kafka \
            --network $NETWORK \
            $IMAGE6
                                     
            sudo docker run -d \
            -p 9093:9092 \
            --name notekafka2 \
            --restart always \
            --env-file env.kafka \
            -e "KAFKA_CFG_CLUSTER_ID=42VMU-JcQ9-5wO8UzA-bAA" \
            -e "KAFKA_CFG_NODE_ID=2" \
            -e "KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://notekafka2:9092" \
            -v $(pwd)/kafka_data2:/bitnami/kafka \
            --network $NETWORK \
            $IMAGE6

            sudo docker run -d \
            -p 9094:9092 \
            --name notekafka3 \
            --restart always \
            --env-file env.kafka \
            -e "KAFKA_CFG_CLUSTER_ID=42VMU-JcQ9-5wO8UzA-bAA" \
            -e "KAFKA_CFG_NODE_ID=3" \
            -e "KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://notekafka3:9092" \
            -v $(pwd)/kafka_data3:/bitnami/kafka \
            --network $NETWORK \
            $IMAGE6

            sudo docker run -d \
             -p 3001:3001 \
             --name http-server \
             --restart always \
             --env-file env.http \
             -e DATABASE_URL="${{secrets.DATABASE_URL}}" \
             --network $NETWORK \
             $IMAGE1

            sudo docker run -d \
            -p 3002:3002 \
            --name filehandler-server \
            --env-file env.redis \
            --network $NETWORK \
            $IMAGE2

            sudo docker run -d \
            -p 3003:3003 \
            --name worker-server \
            --restart always \
            --env-file env.redis \
            -e GROQ_API_KEY="${{secrets.GROQ_API_KEY}}" \
            -e DATABASE_URL="${{secrets.DATABASE_URL}}" \
            --network $NETWORK \
            $IMAGE3

            sudo docker run -d \
            -p 8080:8080  \
            --restart always \
            --name ws-server  \
            --env-file env.redis \
            -e REFRESH_TOKEN_SECRET="${{secrets.REFRESH_TOKEN_SECRET}}" \
            --network $NETWORK \
            $IMAGE4

            sudo docker run -d \
            -p 3000:3000 \
            --name web \
            -e NEXT_PUBLIC_FRONTEND_URL="${{secrets.NEXT_PUBLIC_FRONTEND_URL}}" \
            -e NEXT_PUBLIC_BACKEND_URL="${{secrets.NEXT_PUBLIC_BACKEND_URL}}" \
            -e NEXT_PUBLIC_WEBSOCKET_SERVER="${{secrets.NEXT_PUBLIC_WEBSOCKET_SERVER}}" \
            -e ACCESS_TOKEN_SECRET="${{secrets.ACCESS_TOKEN_SECRET}}" \
            -e REFRESH_TOKEN_SECRET="${{secrets.REFRESH_TOKEN_SECRET}}" \
            -e DATABASE_URL="${{ secrets.DATABASE_URL }}" \
            --network $NETWORK \
            $IMAGE5
            
            sudo docker run -d \
            --name nats-server \
            --restart always \
            -p 4222:4222 \
            -p 8222:8222 \
            -p 6222:6222 \
            -v $(pwd)/nats-server.conf:/etc/nats/nats-server.conf \
            --network $NETWORK \
            $IMAGE7

            
